@startuml abrirTareas-analisis

actor Usuario
boundary TareasView
control TareasController
entity TareaRepository
entity Tarea

Usuario -> TareasView : 1: solicita las tareas
TareasView -> TareasController : 2: pide las tareas
TareasController -> TareaRepository : 3: consulta al repository
TareaRepository -> Tarea : 4: obtener lista de entidades

@enduml
