@startuml abrirTareas-secuencia
!theme plain
autonumber

actor Usuario
participant TareasView <<Capa Presentación UI>>
participant TareasController <<Capa Lógica/Router>>
participant TareasService <<Orquestador de negocio>>
participant TareaRepository <<Capa Datos>>
database PostgreSQL

Usuario -> TareasView : Hace clic
activate TareasView
TareasView -> TareasController : Lanza petición
activate TareasController
TareasController -> TareasService : Delega llamada
activate TareasService
TareasService -> TareaRepository : findAll()
activate TareaRepository
TareaRepository -> PostgreSQL : SELECT * FROM tareas
activate PostgreSQL
PostgreSQL --> TareaRepository : Resultados de la consulta
deactivate PostgreSQL
TareaRepository --> TareasService : Devuelve objetos
deactivate TareaRepository
TareasService --> TareasController : Devuelve objetos
deactivate TareasService
TareasController --> TareasView : Devuelve respuesta
deactivate TareasController
TareasView --> Usuario : Muestra tareas
deactivate TareasView

@enduml
