@startuml completarGestion-analisis
skinparam linetype polyline

actor Usuario
package completarGestion as "completarGestion()" {
    rectangle #629EF9 ResumenGestionView
    rectangle #b5bd68 TareasController
    rectangle #F2AC4E TareaRepository
    rectangle #F2AC4E GrupoRepository
    rectangle #F2AC4E Tarea
    rectangle #F2AC4E Grupo
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> ResumenGestionView: 1: completarGestion()

ResumenGestionView -d-> TareasController: 2: obtenerResumenColaboracion(usuario)

TareasController --> GrupoRepository: 3: obtenerGruposActivos(usuario)
TareasController --> TareaRepository: 4: obtenerTareasPendientes(usuario)

GrupoRepository -- Grupo
TareaRepository -- Tarea

ResumenGestionView -r-> SistemaDisponible: 5: sistemaDisponible(usuario)

@enduml
