@startuml establecerHorario-analisis
skinparam linetype polyline

actor Usuario
package establecerHorario as "establecerHorario()" {
    rectangle #629EF9 HorarioView
    rectangle #b5bd68 PlanificacionController
    rectangle #F2AC4E PlanificacionRepository
    rectangle #F2AC4E Tarea
    rectangle #F2AC4E Horario
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> HorarioView: 1: establecerHorario(tarea)

HorarioView -d-> PlanificacionController: 2: registrarHorario(idTarea, datos)

PlanificacionController --> PlanificacionRepository: 3: establecerHorarioDeTarea(idTarea, datos)

PlanificacionRepository -- Tarea
PlanificacionRepository -- Horario

HorarioView -r-> SistemaDisponible: 4: sistemaDisponible(usuario)

@enduml
