@startuml definirLocalizacion-analisis
skinparam linetype polyline

actor Usuario
package definirLocalizacion as "definirLocalizacion()" {
    rectangle #629EF9 LocalizacionView
    rectangle #b5bd68 PlanificacionController
    rectangle #F2AC4E PlanificacionRepository
    rectangle #F2AC4E Tarea
    rectangle #F2AC4E Localizacion
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> LocalizacionView: 1: definirLocalizacion(tarea)

LocalizacionView -d-> PlanificacionController: 2: registrarLocalizacion(idTarea, datos)

PlanificacionController --> PlanificacionRepository: 3: establecerLocalizacionDeTarea(idTarea, datos)

PlanificacionRepository -- Tarea
PlanificacionRepository -- Localizacion

LocalizacionView -r-> SistemaDisponible: 4: sistemaDisponible(usuario)

@enduml
