@startuml abrirPlanificacion-analisis
skinparam linetype polyline

actor Usuario
package abrirPlanificacion as "abrirPlanificacion()" {
    rectangle #629EF9 PlanificacionView
    rectangle #b5bd68 PlanificacionController
    rectangle #F2AC4E PlanificacionRepository
    rectangle #F2AC4E Tarea
    rectangle #F2AC4E Horario
    rectangle #F2AC4E Localizacion
    rectangle #F2AC4E Recordatorio
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> PlanificacionView: 1: abrirPlanificacion(tarea)

PlanificacionView -d-> PlanificacionController: 2: obtenerDetallesPlanificacion(idTarea)

PlanificacionController --> PlanificacionRepository: 3: buscarConfiguracionCompleta(idTarea)

PlanificacionRepository -- Tarea
PlanificacionRepository -- Horario
PlanificacionRepository -- Localizacion
PlanificacionRepository -- Recordatorio

PlanificacionView -r-> SistemaDisponible: 4: sistemaDisponible(usuario)

@enduml
