@startuml marcarCompletada-analisis
skinparam linetype polyline

actor Usuario
package marcarCompletada as "marcarCompletada()" {
    rectangle #629EF9 ListarTareasView
    rectangle #b5bd68 TareasController
    rectangle #F2AC4E TareaRepository
    rectangle #F2AC4E Tarea
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> ListarTareasView: 1: completarTarea(tarea)

ListarTareasView -d-> TareasController: 2: registrarFinalizacion(idTarea)

TareasController --> TareaRepository: 3: cambiarEstadoACompletada(idTarea)

TareaRepository -- Tarea

ListarTareasView -r-> SistemaDisponible: 4: sistemaDisponible(usuario)

@enduml
