@startuml configurarRecordatorio-analisis
skinparam linetype polyline

actor Usuario
package configurarRecordatorio as "configurarRecordatorio()" {
    rectangle #629EF9 RecordatorioView
    rectangle #b5bd68 PlanificacionController
    rectangle #F2AC4E PlanificacionRepository
    rectangle #F2AC4E Tarea
    rectangle #F2AC4E Recordatorio
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> RecordatorioView: 1: configurarRecordatorio(tarea)

RecordatorioView -d-> PlanificacionController: 2: registrarRecordatorio(idTarea, datos)

PlanificacionController --> PlanificacionRepository: 3: crearRecordatorioParaTarea(idTarea, datos)

PlanificacionRepository -- Tarea
PlanificacionRepository -- Recordatorio

RecordatorioView -r-> SistemaDisponible: 4: sistemaDisponible(usuario)

@enduml
