@startuml cerrarSesion-analisis
skinparam linetype polyline

actor Usuario
package cerrarSesion as "cerrarSesion()" {
    rectangle #629EF9 MainView
    rectangle #b5bd68 SesionController
    rectangle #F2AC4E SesionRepository
    rectangle #F2AC4E Sesion
}
rectangle #CDEBA5 ":Sistema No Disponible" as SistemaNoDisponible

Usuario -r-> MainView: 1: cerrarSesion()

MainView -d-> SesionController: 2: finalizarSesion()

SesionController --> SesionRepository: 3: invalidarSesionActual()

SesionRepository -- Sesion

MainView -r-> SistemaNoDisponible: 4: sistemaNoDisponible()

@enduml
