@startuml asignarTareaAUsuario-analisis
skinparam linetype polyline

actor Usuario
package asignarTareaAUsuario as "asignarTareaAUsuario()" {
    rectangle #629EF9 AsignacionView
    rectangle #b5bd68 PlanificacionController
    rectangle #F2AC4E PlanificacionRepository
    rectangle #F2AC4E Tarea
    rectangle #F2AC4E Usuario as UserEnt
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> AsignacionView: 1: asignarTarea(tarea)

AsignacionView -d-> PlanificacionController: 2: registrarAsignacion(idTarea, idUsuario)

PlanificacionController --> PlanificacionRepository: 3: vincularResponsable(idTarea, idUsuario)

PlanificacionRepository -- Tarea
PlanificacionRepository -- UserEnt

AsignacionView -r-> SistemaDisponible: 4: sistemaDisponible(usuario)

@enduml
